PROGRAM_NAME="push_swap"
TEST_OUTPUT_FILES="../test_output_files/"
TEST_ERROR_FILES="../test_error_files/"
TEST_100="test_100/"
TEST_500="test_500/"
FILE_NAME_100_OUTPUT="test_100_numbers_output"
FILE_NAME_100_ERROR="test_100_numbers_error"
FILE_NAME_500_OUTPUT="test_500_numbers_output"
FILE_NAME_500_ERROR="test_500_numbers_error"
FILE_NAME_END=".txt"

ERROR_FILES_100_AMOUNT=0
ERROR_FILES_500_AMOUNT=0

BLACK="\033[30m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
MAGENTA="\033[35m"
CYAN="\033[36m"
WHITE="\033[37m"
SUPER_RED="\033[91m"
SUPER_GREEN="\033[92m"
SUPER_YELLOW="\033[93m"
SUPER_BLUE="\033[94m"
SUPER_MAGENTA="\033[95m"
SUPER_CYAN="\033[96m"

test $TEST_OUTPUT_FILES | mkdir $TEST_OUTPUT_FILES
test $TEST_ERROR_FILES | mkdir $TEST_ERROR_FILES
test $TEST_OUTPUT_FILES$TEST_100 | mkdir $TEST_OUTPUT_FILES$TEST_100
test $TEST_ERROR_FILES$TEST_100 | mkdir $TEST_ERROR_FILES$TEST_100
test $TEST_OUTPUT_FILES$TEST_500 | mkdir $TEST_OUTPUT_FILES$TEST_500
test $TEST_ERROR_FILES$TEST_500 | mkdir $TEST_ERROR_FILES$TEST_500
echo "$YELLOW Testing 100 times with 100 random numbers$WHITE"
for i in $(seq 1 100); do 
	../../$PROGRAM_NAME $(shuf -i 0-500 -n 100) > $TEST_OUTPUT_FILES$TEST_100$FILE_NAME_100_OUTPUT$i$FILE_NAME_END 2>$TEST_ERROR_FILES$TEST_100$FILE_NAME_100_ERROR$i$FILE_NAME_END;
done
for i in $(seq 1 100); do
	LINES=$(wc -l < "$TEST_ERROR_FILES$TEST_100$FILE_NAME_100_ERROR$i$FILE_NAME_END");
	if [ "$LINES" -eq 0 ]; then
		rm "$TEST_ERROR_FILES$TEST_100$FILE_NAME_100_ERROR$i$FILE_NAME_END";
	else
		ERROR_FILES_100_AMOUNT=$(($ERROR_FILES_100_AMOUNT + 1))
	fi;
done
if [ "$(find $TEST_ERROR_FILES$TEST_100 -type f -name ".txt" | wc -l )" -gt "0" ]; then
	echo "$SUPER_RED Deu B.O. em $TEST_ERROR_FILES$TEST_100 $ERROR_FILES_100_AMOUNT errors :($WHITE";
else
	echo "$SUPER_GREEN De boa sacana: $ERROR_FILES_100_AMOUNT errors$WHITE";
fi;
echo "$YELLOW Testing 100 times with 500 random numbers$WHITE"
echo "$SUPER_RED Be patient it takes some time$WHITE"
for i in $(seq 1 100); do
	../../$PROGRAM_NAME $(shuf -i 0-5000 -n 500) > $TEST_OUTPUT_FILES$TEST_500$FILE_NAME_500_OUTPUT$i$FILE_NAME_END 2>$TEST_ERROR_FILES$TEST_500$FILE_NAME_500_ERROR$i$FILE_NAME_END;
done
for i in $(seq 1 100); do
	LINES=$(wc -l < "$TEST_ERROR_FILES$TEST_500$FILE_NAME_500_ERROR$i$FILE_NAME_END");
	if [ "$LINES" -eq 0 ]; then
		rm "$TEST_ERROR_FILES$TEST_500$FILE_NAME_500_ERROR$i$FILE_NAME_END";
	else
		ERROR_FILES_500_AMOUNT=$(($ERROR_FILES_500_AMOUNT + 1))
	fi;
done
if [ "$(find $TEST_ERROR_FILES$TEST_500 -type f -name ".txt" | wc -l )" -gt "0" ]; then
	echo "$SUPER_RED Deu B.O. em $TEST_ERROR_FILES$TEST_500 $ERROR_FILES_500_AMOUNT errors :($WHITE";
else
	echo "$SUPER_GREEN De boa sacana: $ERROR_FILES_500_AMOUNT errors$WHITE";
fi;
echo "$GREEN Files are ready to be tested!$WHITE"